name: tests

on:
  push:
  pull_request:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      # Let PHACC discover your custom integration
      PYTEST_HOMEASSISTANT_CUSTOM_COMPONENTS: ${{ github.workspace }}/custom_components

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            requirements_test.txt

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      - name: Sanity - show tree
        run: |
          ls -la
          ls -la custom_components || true
          ls -la custom_components/fertility_tracker || true
          python - <<'PY'
          import pathlib, json
          p = pathlib.Path("custom_components/fertility_tracker/manifest.json")
          print("manifest exists:", p.exists())
          if p.exists():
              print("manifest:", json.loads(p.read_text()))
          PY

      - name: Run pytest
        run: pytest --maxfail=1 --durations=20 -q
