name: validate

on:
  push:
  pull_request:

jobs:
  hassfest:
    name: hassfest validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master

  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate with HACS
        uses: hacs/action@main
        with:
          category: "integration"   # your repo is an Integration
          ignore: "brands"          # remove if you add a brand dir
